# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [2]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [3]:
print(np.__version__)


1.19.5


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [4]:
a = np.random.rand(2, 3, 5)
print (a.shape)
print(a)


(2, 3, 5)
[[[0.43231862 0.17882843 0.85707644 0.68068415 0.41732833]
  [0.13647057 0.54275477 0.37519793 0.72801373 0.27184358]
  [0.05609457 0.8133588  0.22420638 0.39748148 0.79335871]]

 [[0.01813091 0.63477216 0.71831781 0.47107478 0.8023688 ]
  [0.01730773 0.22955624 0.74155437 0.76910881 0.21431259]
  [0.3822671  0.39682359 0.99661836 0.15770422 0.05710333]]]



### 4. Print a.


In [5]:
print(a)


[[[0.43231862 0.17882843 0.85707644 0.68068415 0.41732833]
  [0.13647057 0.54275477 0.37519793 0.72801373 0.27184358]
  [0.05609457 0.8133588  0.22420638 0.39748148 0.79335871]]

 [[0.01813091 0.63477216 0.71831781 0.47107478 0.8023688 ]
  [0.01730773 0.22955624 0.74155437 0.76910881 0.21431259]
  [0.3822671  0.39682359 0.99661836 0.15770422 0.05710333]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [6]:
b = np.ones((5,2,3))
print(b.shape)
print(b)

(5, 2, 3)
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 6. Print b.


In [7]:
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [8]:
print(a.shape==b.shape)


False



### 8. Are you able to add a and b? Why or why not?


In [9]:
c= a + b
print(c)


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [ ]:
Is not possible to add a and b because 3 and 5 from a are not expandable to 2 and 3 from b. 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [10]:
c= b.transpose(1,2,0)
print(c.shape)

(2, 3, 5)


In [11]:
a.shape

(2, 3, 5)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [12]:
d = a + c
print(d.shape)
print(a.shape)


(2, 3, 5)
(2, 3, 5)


In [ ]:
a and c can be added ad a anc d are the same shape


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [14]:
print(a)

[[[0.43231862 0.17882843 0.85707644 0.68068415 0.41732833]
  [0.13647057 0.54275477 0.37519793 0.72801373 0.27184358]
  [0.05609457 0.8133588  0.22420638 0.39748148 0.79335871]]

 [[0.01813091 0.63477216 0.71831781 0.47107478 0.8023688 ]
  [0.01730773 0.22955624 0.74155437 0.76910881 0.21431259]
  [0.3822671  0.39682359 0.99661836 0.15770422 0.05710333]]]


In [15]:
print(d)

[[[1.43231862 1.17882843 1.85707644 1.68068415 1.41732833]
  [1.13647057 1.54275477 1.37519793 1.72801373 1.27184358]
  [1.05609457 1.8133588  1.22420638 1.39748148 1.79335871]]

 [[1.01813091 1.63477216 1.71831781 1.47107478 1.8023688 ]
  [1.01730773 1.22955624 1.74155437 1.76910881 1.21431259]
  [1.3822671  1.39682359 1.99661836 1.15770422 1.05710333]]]



### 12. Multiply a and c. Assign the result to e.


In [16]:
e = a * c
print(e)


[[[0.43231862 0.17882843 0.85707644 0.68068415 0.41732833]
  [0.13647057 0.54275477 0.37519793 0.72801373 0.27184358]
  [0.05609457 0.8133588  0.22420638 0.39748148 0.79335871]]

 [[0.01813091 0.63477216 0.71831781 0.47107478 0.8023688 ]
  [0.01730773 0.22955624 0.74155437 0.76910881 0.21431259]
  [0.3822671  0.39682359 0.99661836 0.15770422 0.05710333]]]




### 13. Does e equal to a? Why or why not?


In [17]:
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [18]:
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)

print(d_max)
print(d_min)
print(d_mean)


1.9966183588274462
1.0173077283552239
1.4504012427788786



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [19]:
f=np.empty(d.shape)




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [20]:
import pandas as pd

In [22]:
d_flat = pd.Series(d.flatten())
d_min, d_mean, d_max = d_flat.min(), d_flat.mean(), d_flat.max()
f_flat = pd.Series(0, index=d_flat.index)  


In [23]:
f_flat[(d_flat > d_min) & (d_flat < d_mean)] = 25
f_flat[(d_flat > d_mean) & (d_flat < d_max)] = 75
f_flat[d_flat == d_mean] = 50
f_flat[d_flat == d_max] = 100

In [24]:

f = f_flat.values.reshape(d.shape)
f

array([[[ 25,  25,  75,  75,  25],
        [ 25,  75,  25,  75,  25],
        [ 25,  75,  25,  25,  75]],

       [[ 25,  75,  75,  75,  75],
        [  0,  25,  75,  75,  25],
        [ 25,  25, 100,  25,  25]]], dtype=int64)





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [25]:
d_flat = pd.Series(d.ravel())
d_min, d_mean, d_max = d_flat.min(), d_flat.mean(), d_flat.max()
f_flat = pd.Series(0, index=d_flat.index, dtype=float)

In [26]:
f_flat[(d_flat > d_min) & (d_flat < d_mean)] = 25
f_flat[(d_flat > d_mean) & (d_flat < d_max)] = 75
f_flat[d_flat == d_mean] = 50
f_flat[d_flat == d_max] = 100

In [27]:
f = f_flat.values.reshape(d.shape)
f

array([[[ 25.,  25.,  75.,  75.,  25.],
        [ 25.,  75.,  25.,  75.,  25.],
        [ 25.,  75.,  25.,  25.,  75.]],

       [[ 25.,  75.,  75.,  75.,  75.],
        [  0.,  25.,  75.,  75.,  25.],
        [ 25.,  25., 100.,  25.,  25.]]])

### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [37]:
d_flat_bonus = pd.Series(d.ravel())
d_min, d_mean, d_max = d_flat_bonus.min(), d_flat_bonus.mean(), d_flat_bonus.max()
f_flat_bonus = pd.Series("", index=d_flat_bonus.index, dtype=object)

In [38]:
f_flat_bonus[d_flat_bonus == d_min] = "A"
f_flat_bonus[(d_flat_bonus > d_min) & (d_flat_bonus < d_mean)] = "B"
f_flat_bonus[d_flat_bonus == d_mean] = "C"
f_flat_bonus[(d_flat_bonus > d_mean) & (d_flat < d_max)] = "D"
f_flat_bonus[d_flat_bonus == d_max] = "E"

In [39]:
f_flat_bonus = f_flat_bonus.values.reshape(d.shape)

In [40]:
f_flat_bonus

array([[['B', 'B', 'D', 'D', 'B'],
        ['B', 'D', 'B', 'D', 'B'],
        ['B', 'D', 'B', 'B', 'D']],

       [['B', 'D', 'D', 'D', 'D'],
        ['A', 'B', 'D', 'D', 'B'],
        ['B', 'B', 'E', 'B', 'B']]], dtype=object)